version: '3'

services:
    frontend:
        container_name: frontend
        build:
            context: .
        volumes:
            - .:/app
        ports:
            - 8080:8080
        tty: true
        environment:
            NODE_OPTIONS: --openssl-legacy-provider
